select 'Consulta 1';
select pel_titulo from peliculas UNION select ser_titulo from series order by pel_titulo;
select 'Consulta 2';
select pel_titulo, pel_resumen, pel_anio from peliculas where pel_anio > '2000' order by pel_titulo;
select 'Consulta 3';
select pel_titulo from peliculas where dir_id_fk =105;
select 'Consulta 4';
select trans_cont from transmisiones where usu_alias_fk = 'lucky' order by trans_cont;
select 'Consulta 5';
select usu_alias, usu_nombre, usu_apellido from usuarios inner join transmisiones where usuarios.usu_alias=transmisiones.usu_alias_fk and trans_cont = 'Interestelar';
select 'Consulta 6';
select count(pel_id) from peliculas where pel_anio > 2000;